CREATE TABLE IF NOT EXISTS CRAWLER_FAILURE_HISTORY (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  TARGET_DATE DATE NOT NULL,
  INDICATOR_CODE VARCHAR(32) NOT NULL,
  INDICATOR_NAME VARCHAR(100) NULL,
  SOURCE_NAME VARCHAR(100) NOT NULL,
  CRAWLER_NAME VARCHAR(150) NULL,
  FAILURE_STAGE VARCHAR(100) NOT NULL,
  FAILURE_REASON VARCHAR(255) NULL,
  ERROR_MESSAGE VARCHAR(1000) NULL,
  ATTEMPT_NO INT UNSIGNED NOT NULL DEFAULT 1,
  RETRY_COUNT INT UNSIGNED NOT NULL DEFAULT 0,
  RESOLVED_YN CHAR(1) NOT NULL DEFAULT 'N',
  PROCESSED_YN CHAR(1) NOT NULL DEFAULT 'N',
  RESOLVED_AT DATETIME NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY uq_crawler_failure_target_indicator_source (
    TARGET_DATE,
    INDICATOR_CODE,
    SOURCE_NAME
  ),
  KEY idx_crawler_failure_unresolved (RESOLVED_YN, TARGET_DATE),
  KEY idx_crawler_failure_processed (PROCESSED_YN, TARGET_DATE),
  KEY idx_crawler_failure_updated (UPDATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
