-- Finmap market weekly recheck tables
-- File: sql/20260502_create_market_weekly_recheck_tables.sql
--
-- Scope:
--   신규 검증 테이블 생성만 수행한다.
--   운영 테이블(MARKETS_WORLD_INDICES_INFO, STOCK_INVEST_INFO,
--   MARKET_SITE_ETF_STOCK_INFO 등)에는 ALTER/UPDATE/DELETE/INSERT 하지 않는다.
--
-- Operational DDL status:
--   repo 안에서 운영 3개 마켓 테이블의 CREATE TABLE DDL은 확인되지 않았다.
--   코드 기준 날짜 key 값은 moment/dayjs format('YYYY-MM-DD')로 생성되어 DB에 전달된다.
--   따라서 stage 테이블의 운영 key 날짜 컬럼은 DATE로 고정하지 않고 VARCHAR(10)으로 둔다.
--   운영 DDL 확인 후 실제 타입이 DATE이면 stage도 DATE로 맞추는 것을 검토한다.
--
-- JSON compatibility:
--   운영 MySQL 버전 호환성을 위해 targets/raw_json/key_json은 기본 LONGTEXT로 둔다.
--   MySQL 5.7+ JSON 타입을 확실히 사용할 수 있으면 각 컬럼을 JSON으로 바꿀 수 있다.
--
-- Foreign key policy:
--   기본 DDL에는 FK를 걸지 않는다. 배치/재검증 테이블은 run_id 인덱스와 unique key만으로도
--   조회/비교/삭제 단위를 충분히 제한할 수 있고, 운영 적용 시 FK 검증 비용/잠금 리스크가 작다.
--   FK가 필요하면 파일 하단의 "FK optional" 섹션을 별도 검토 후 적용한다.

-- ============================================================================
-- 1차 적용: run, world-index stage, stock-invest stage, diff
-- ============================================================================

CREATE TABLE IF NOT EXISTS MARKET_WEEKLY_RECHECK_RUN (
  run_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  week_start_date DATE NOT NULL COMMENT '검증 주의 월요일',
  week_end_date DATE NOT NULL COMMENT '검증 주의 금요일',
  target_from_date DATE NOT NULL COMMENT '재수집 대상 시작일',
  target_to_date DATE NOT NULL COMMENT '재수집 대상 종료일',
  status ENUM('PENDING','RUNNING','SUCCESS','PARTIAL_FAILED','FAILED') NOT NULL DEFAULT 'PENDING',
  targets LONGTEXT NULL COMMENT 'JSON text. 예: ["MARKETS_WORLD_INDICES_INFO","STOCK_INVEST_INFO"]',
  -- MySQL 5.7+ JSON 확정 시 대체 가능:
  -- targets JSON NULL COMMENT '검증 대상 테이블/소스 목록',
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  total_count INT UNSIGNED NOT NULL DEFAULT 0,
  success_count INT UNSIGNED NOT NULL DEFAULT 0,
  fail_count INT UNSIGNED NOT NULL DEFAULT 0,
  diff_count INT UNSIGNED NOT NULL DEFAULT 0,
  high_diff_count INT UNSIGNED NOT NULL DEFAULT 0,
  message VARCHAR(1000) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (run_id),
  KEY idx_market_weekly_run_week (week_start_date, week_end_date),
  KEY idx_market_weekly_run_target (target_from_date, target_to_date),
  KEY idx_market_weekly_run_status (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS MARKETS_WORLD_INDICES_INFO_WEEKLY_STAGE (
  stage_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id BIGINT UNSIGNED NOT NULL,
  week_start_date DATE NOT NULL,
  week_end_date DATE NOT NULL,
  collected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_run_type ENUM('BF','AF_OPEN','AF_CLOSE','ROLLUP','MANUAL','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  raw_json LONGTEXT NULL COMMENT 'JSON text. 원천 응답/정규화 전 값',
  -- MySQL 5.7+ JSON 확정 시 대체 가능:
  -- raw_json JSON NULL COMMENT '원천 응답/정규화 전 값',

  INDEX_DATE VARCHAR(10) NOT NULL COMMENT '운영 DDL 확인 필요. 코드 입력값은 YYYY-MM-DD',
  INDEX_ID VARCHAR(32) NOT NULL,
  INDEX_SITE_ID VARCHAR(32) NOT NULL,
  INDEX_SITE_NAME VARCHAR(100) NULL,
  KSP_STOCK_DATE VARCHAR(10) NULL COMMENT '운영 DDL 확인 필요. 코드 입력값은 YYYY-MM-DD',
  US_HOLYDAY_YN CHAR(1) NULL,
  KR_HOLYDAY_YN CHAR(1) NULL,
  IF_SUCC_YN CHAR(1) NULL,

  -- 숫자 precision/scale은 운영 DDL 확인 필요. 코드 계산은 주로 소수 2자리지만 여유를 둔다.
  INDEX_STD_PRICE DECIMAL(20,6) NULL,
  INDEX_MDF_STD_PRICE DECIMAL(20,6) NULL,
  INDEX_OPEN_PRICE DECIMAL(20,6) NULL,
  INDEX_HIGH_PRICE DECIMAL(20,6) NULL,
  INDEX_LOW_PRICE DECIMAL(20,6) NULL,
  INDEX_END_PRICE DECIMAL(20,6) NULL,
  INDEX_UD_PRICE DECIMAL(20,6) NULL,
  INDEX_UD_RATE_REAL_BY_OPEN DECIMAL(20,6) NULL,
  INDEX_UD_RATE_REAL_BY_HIGH DECIMAL(20,6) NULL,
  INDEX_UD_RATE_REAL_BY_LOW DECIMAL(20,6) NULL,
  INDEX_UD_RATE_REAL_BY_TODAY DECIMAL(20,6) NULL,
  INDEX_UD_RATE_REAL_BY_CLOSE DECIMAL(20,6) NULL,
  INDEX_SCORE DECIMAL(20,6) NULL,

  -- USD/KRW 등 보조 기준값. 모든 INDEX_ID에서 채워지는 컬럼은 아니다.
  INDEX_EXTR1_STD_PRICE DECIMAL(20,6) NULL,
  INDEX_EXTR1_END_PRICE DECIMAL(20,6) NULL,
  INDEX_EXTR1_UD_PRICE DECIMAL(20,6) NULL,
  INDEX_EXTR1_UD_RATE_REAL_BY_OPEN DECIMAL(20,6) NULL,
  INDEX_EXTR1_UD_RATE_REAL_BY_TODAY DECIMAL(20,6) NULL,
  INDEX_EXTR1_UD_RATE_REAL_BY_CLOSE DECIMAL(20,6) NULL,
  INDEX_EXTR1_SCORE DECIMAL(20,6) NULL,

  INDEX_EXTR2_STD_PRICE DECIMAL(20,6) NULL,
  INDEX_EXTR2_END_PRICE DECIMAL(20,6) NULL,
  INDEX_EXTR2_UD_PRICE DECIMAL(20,6) NULL,
  INDEX_EXTR2_UD_RATE_REAL_BY_OPEN DECIMAL(20,6) NULL,
  INDEX_EXTR2_UD_RATE_REAL_BY_TODAY DECIMAL(20,6) NULL,
  INDEX_EXTR2_UD_RATE_REAL_BY_CLOSE DECIMAL(20,6) NULL,
  INDEX_EXTR2_SCORE DECIMAL(20,6) NULL,

  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (stage_id),
  UNIQUE KEY uk_mwii_stage_run_key (run_id, INDEX_DATE, INDEX_ID, INDEX_SITE_ID),
  KEY idx_mwii_stage_date (INDEX_DATE, INDEX_ID, INDEX_SITE_ID),
  KEY idx_mwii_stage_run_date (run_id, INDEX_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS STOCK_INVEST_INFO_WEEKLY_STAGE (
  stage_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id BIGINT UNSIGNED NOT NULL,
  week_start_date DATE NOT NULL,
  week_end_date DATE NOT NULL,
  collected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_run_type ENUM('BF','AF_OPEN','AF_CLOSE','ROLLUP','MANUAL','UNKNOWN') NOT NULL DEFAULT 'ROLLUP',
  raw_json LONGTEXT NULL COMMENT 'JSON text. 최종 집계 입력/결과 snapshot',
  -- MySQL 5.7+ JSON 확정 시 대체 가능:
  -- raw_json JSON NULL COMMENT '최종 집계 입력/결과 snapshot',

  KSP_STOCK_DATE VARCHAR(10) NOT NULL COMMENT '운영 DDL 확인 필요. 코드 입력값은 YYYY-MM-DD',
  KSP_BF_STOCK_DATE VARCHAR(10) NULL COMMENT '운영 DDL 확인 필요. 코드 입력값은 YYYY-MM-DD',
  US_HOLYDAY_YN CHAR(1) NULL,
  KR_HOLYDAY_YN CHAR(1) NULL,
  IF_SUCC_YN CHAR(1) NULL,

  KSP_BEF_CLOSE_PRICE DECIMAL(20,6) NULL,
  KSP_OPEN_PRICE DECIMAL(20,6) NULL,
  KSP_HIGH_PRICE DECIMAL(20,6) NULL,
  KSP_LOW_PRICE DECIMAL(20,6) NULL,
  KSP_CLOSE_PRICE DECIMAL(20,6) NULL,
  KSP_TODAY_DIFF_PRICE DECIMAL(20,6) NULL,
  KSP_UD_RATE_REAL_BY_OPEN DECIMAL(20,6) NULL,
  KSP_UD_RATE_REAL_BY_HIGH DECIMAL(20,6) NULL,
  KSP_UD_RATE_REAL_BY_LOW DECIMAL(20,6) NULL,
  KSP_UD_RATE_REAL_BY_TODAY DECIMAL(20,6) NULL,
  KSP_UD_RATE_REAL_BY_CLOSE DECIMAL(20,6) NULL,
  BF_KSP_OPEN_DO_YN CHAR(1) NULL,
  AF_KSP_OPEN_DO_YN CHAR(1) NULL,
  CLOSE_KSP_OPEN_DO_YN CHAR(1) NULL COMMENT 'API에서 조회. 현재 집계 코드 내 직접 세팅 여부는 확인 필요',

  SNP_STD_PRICE DECIMAL(20,6) NULL,
  SNP_OPEN_PRICE DECIMAL(20,6) NULL,
  SNP_END_PRICE DECIMAL(20,6) NULL,
  SNP_UD_PRICE DECIMAL(20,6) NULL,
  SNP_UD_RATE_REAL_BY_OPEN DECIMAL(20,6) NULL,
  SNP_UD_RATE_REAL_BY_TODAY DECIMAL(20,6) NULL,
  SNP_UD_RATE_REAL_BY_CLOSE DECIMAL(20,6) NULL,
  SNP_SCORE DECIMAL(20,6) NULL,
  SNP_OPEN_DO_YN CHAR(1) NULL,

  NDQ_STD_PRICE DECIMAL(20,6) NULL,
  NDQ_OPEN_PRICE DECIMAL(20,6) NULL,
  NDQ_END_PRICE DECIMAL(20,6) NULL,
  NDQ_UD_PRICE DECIMAL(20,6) NULL,
  NDQ_UD_RATE_REAL_BY_OPEN DECIMAL(20,6) NULL,
  NDQ_UD_RATE_REAL_BY_TODAY DECIMAL(20,6) NULL,
  NDQ_UD_RATE_REAL_BY_CLOSE DECIMAL(20,6) NULL,
  NDQ_SCORE DECIMAL(20,6) NULL,
  NDQ_OPEN_DO_YN CHAR(1) NULL,

  DWJ_STD_PRICE DECIMAL(20,6) NULL,
  DWJ_OPEN_PRICE DECIMAL(20,6) NULL,
  DWJ_END_PRICE DECIMAL(20,6) NULL,
  DWJ_UD_PRICE DECIMAL(20,6) NULL,
  DWJ_UD_RATE_REAL_BY_OPEN DECIMAL(20,6) NULL,
  DWJ_UD_RATE_REAL_BY_TODAY DECIMAL(20,6) NULL,
  DWJ_UD_RATE_REAL_BY_CLOSE DECIMAL(20,6) NULL,
  DWJ_SCORE DECIMAL(20,6) NULL,
  DWJ_OPEN_DO_YN CHAR(1) NULL,

  DXY_STD_PRICE DECIMAL(20,6) NULL,
  DXY_OPEN_PRICE DECIMAL(20,6) NULL,
  DXY_END_PRICE DECIMAL(20,6) NULL,
  DXY_UD_PRICE DECIMAL(20,6) NULL,
  DXY_UD_RATE_REAL_BY_OPEN DECIMAL(20,6) NULL,
  DXY_UD_RATE_REAL_BY_TODAY DECIMAL(20,6) NULL,
  DXY_UD_RATE_REAL_BY_CLOSE DECIMAL(20,6) NULL,
  DXY_SCORE DECIMAL(20,6) NULL,
  DXY_OPEN_DO_YN CHAR(1) NULL,

  TNX_STD_PRICE DECIMAL(20,6) NULL,
  TNX_OPEN_PRICE DECIMAL(20,6) NULL,
  TNX_END_PRICE DECIMAL(20,6) NULL,
  TNX_UD_PRICE DECIMAL(20,6) NULL,
  TNX_UD_RATE_REAL_BY_OPEN DECIMAL(20,6) NULL,
  TNX_UD_RATE_REAL_BY_TODAY DECIMAL(20,6) NULL,
  TNX_UD_RATE_REAL_BY_CLOSE DECIMAL(20,6) NULL,
  TNX_SCORE DECIMAL(20,6) NULL,
  TNX_OPEN_DO_YN CHAR(1) NULL,

  WTI_STD_PRICE DECIMAL(20,6) NULL,
  WTI_OPEN_PRICE DECIMAL(20,6) NULL,
  WTI_END_PRICE DECIMAL(20,6) NULL,
  WTI_UD_PRICE DECIMAL(20,6) NULL,
  WTI_UD_RATE_REAL_BY_OPEN DECIMAL(20,6) NULL,
  WTI_UD_RATE_REAL_BY_TODAY DECIMAL(20,6) NULL,
  WTI_UD_RATE_REAL_BY_CLOSE DECIMAL(20,6) NULL,
  WTI_SCORE DECIMAL(20,6) NULL,
  WTI_OPEN_DO_YN CHAR(1) NULL,

  KRW_STD_PRICE DECIMAL(20,6) NULL,
  KRW_OPEN_PRICE DECIMAL(20,6) NULL,
  KRW_END_PRICE DECIMAL(20,6) NULL,
  KRW_UD_PRICE DECIMAL(20,6) NULL,
  KRW_UD_RATE_REAL_BY_OPEN DECIMAL(20,6) NULL,
  KRW_UD_RATE_REAL_BY_TODAY DECIMAL(20,6) NULL,
  KRW_UD_RATE_REAL_BY_CLOSE DECIMAL(20,6) NULL,
  KRW_SCORE DECIMAL(20,6) NULL,
  KRW_OPEN_DO_YN CHAR(1) NULL,

  GROWTH_TOT_SCORE DECIMAL(20,6) NULL,
  PRICE_TOT_SCORE DECIMAL(20,6) NULL,
  GROWTH_TOT_SCORE_GRADE SMALLINT NULL,
  PRICE_TOT_SCORE_GRADE SMALLINT NULL,
  PRC_SET_RNG_GRP SMALLINT NULL,
  PARENT_GROWTH_TOT_SCORE_GRADE SMALLINT NULL,
  PARENT_PRC_SET_RNG_GRP SMALLINT NULL,

  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (stage_id),
  UNIQUE KEY uk_stock_stage_run_key (run_id, KSP_STOCK_DATE),
  KEY idx_stock_stage_date (KSP_STOCK_DATE),
  KEY idx_stock_stage_run_date (run_id, KSP_STOCK_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS MARKET_WEEKLY_RECHECK_DIFF (
  diff_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id BIGINT UNSIGNED NOT NULL,
  table_name VARCHAR(80) NOT NULL,
  diff_type ENUM('MISSING_IN_MAIN','MISSING_IN_STAGE','VALUE_DIFF','FLAG_DIFF','ONLY_METADATA_DIFF') NOT NULL,
  target_date VARCHAR(10) NOT NULL COMMENT '비교 대상 운영 날짜 key. 코드 기준 YYYY-MM-DD',
  key_json LONGTEXT NOT NULL COMMENT 'canonical JSON text. key_hash가 unique 기준이므로 JSON 타입 필수 아님',
  -- MySQL 5.7+ JSON 확정 시 대체 가능:
  -- key_json JSON NOT NULL COMMENT '비교 key JSON',
  key_hash BINARY(32) NOT NULL COMMENT '앱에서 UNHEX(SHA2(canonical key_json, 256)) 형태로 계산 권장',
  indicator_code VARCHAR(32) NULL,
  source_id VARCHAR(32) NULL,
  column_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'row-level diff는 빈 문자열',
  main_value LONGTEXT NULL,
  stage_value LONGTEXT NULL,
  diff_value DECIMAL(30,10) NULL,
  tolerance DECIMAL(30,10) NULL,
  severity ENUM('HIGH','MEDIUM','LOW') NOT NULL DEFAULT 'MEDIUM',
  resolved_yn CHAR(1) NOT NULL DEFAULT 'N',
  note VARCHAR(1000) NULL,
  checked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (diff_id),
  UNIQUE KEY uk_market_weekly_diff (run_id, table_name, diff_type, key_hash, column_name),
  KEY idx_market_weekly_diff_run_severity (run_id, severity, diff_type),
  KEY idx_market_weekly_diff_table_date (table_name, target_date),
  KEY idx_market_weekly_diff_indicator (indicator_code, source_id),
  KEY idx_market_weekly_diff_resolved (resolved_yn, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- 2차 적용 옵션: ETF stage, tolerance rule
-- 아래 블록은 1차 운영 적용 범위에서 제외하려고 주석 처리한다.
-- 필요 시 블록 주석을 제거하고 별도 검토 후 적용한다.
-- ============================================================================

/*
CREATE TABLE IF NOT EXISTS MARKET_SITE_ETF_STOCK_INFO_WEEKLY_STAGE (
  stage_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id BIGINT UNSIGNED NOT NULL,
  week_start_date DATE NOT NULL,
  week_end_date DATE NOT NULL,
  collected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_run_type ENUM('AF_OPEN','AF_CLOSE','MANUAL','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  raw_json LONGTEXT NULL COMMENT 'JSON text. MySQL 5.7+ 확정 시 JSON 타입으로 변경 가능',

  ETF_STOCK_DATE VARCHAR(10) NOT NULL COMMENT '운영 DDL 확인 필요. 코드 입력값은 YYYY-MM-DD',
  ETF_STOCK_ID VARCHAR(32) NOT NULL,
  ETF_SITE_ID VARCHAR(32) NOT NULL,
  ETF_SITE_NAME VARCHAR(100) NULL,
  ETF_STOCK_NAME VARCHAR(150) NULL,
  ETF_BF_STOCK_DATE VARCHAR(10) NULL COMMENT '운영 DDL 확인 필요. 코드 입력값은 YYYY-MM-DD',
  ETF_BEF_CLOSE_PRICE DECIMAL(20,6) NULL,
  ETF_OPEN_PRICE DECIMAL(20,6) NULL,
  ETF_HIGH_PRICE DECIMAL(20,6) NULL,
  ETF_LOW_PRICE DECIMAL(20,6) NULL,
  ETF_CLOSE_PRICE DECIMAL(20,6) NULL,
  ETF_TODAY_DIFF_PRICE DECIMAL(20,6) NULL,
  ETF_UD_RATE_REAL_BY_OPEN DECIMAL(20,6) NULL,
  ETF_UD_RATE_REAL_BY_HIGH DECIMAL(20,6) NULL,
  ETF_UD_RATE_REAL_BY_LOW DECIMAL(20,6) NULL,
  ETF_UD_RATE_REAL_BY_TODAY DECIMAL(20,6) NULL,
  ETF_UD_RATE_REAL_BY_CLOSE DECIMAL(20,6) NULL,
  AFTER_ETF_OPEN_DO_YN CHAR(1) NULL,
  CLOSE_ETF_OPEN_DO_YN CHAR(1) NULL,

  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (stage_id),
  UNIQUE KEY uk_etf_stage_run_key (run_id, ETF_STOCK_DATE, ETF_STOCK_ID, ETF_SITE_ID),
  KEY idx_etf_stage_date (ETF_STOCK_DATE, ETF_STOCK_ID, ETF_SITE_ID),
  KEY idx_etf_stage_run_date (run_id, ETF_STOCK_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS MARKET_WEEKLY_RECHECK_TOLERANCE_RULE (
  rule_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  table_name VARCHAR(80) NOT NULL,
  column_match_type ENUM('EXACT','LIKE') NOT NULL DEFAULT 'EXACT',
  column_name VARCHAR(128) NOT NULL COMMENT 'EXACT 컬럼명 또는 LIKE 패턴',
  value_type ENUM('NUMERIC','FLAG','STRING','DATE') NOT NULL DEFAULT 'NUMERIC',
  tolerance DECIMAL(30,10) NOT NULL DEFAULT 0,
  default_severity ENUM('HIGH','MEDIUM','LOW') NOT NULL DEFAULT 'MEDIUM',
  enabled_yn CHAR(1) NOT NULL DEFAULT 'Y',
  note VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (rule_id),
  UNIQUE KEY uk_market_weekly_tol_rule (table_name, column_match_type, column_name),
  KEY idx_market_weekly_tol_enabled (enabled_yn, table_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO MARKET_WEEKLY_RECHECK_TOLERANCE_RULE
  (table_name, column_match_type, column_name, value_type, tolerance, default_severity, note)
VALUES
  ('MARKETS_WORLD_INDICES_INFO', 'LIKE', 'INDEX_%PRICE', 'NUMERIC', 0.01, 'MEDIUM', 'index price columns'),
  ('MARKETS_WORLD_INDICES_INFO', 'LIKE', 'INDEX_%RATE%', 'NUMERIC', 0.01, 'MEDIUM', 'index rate columns'),
  ('MARKETS_WORLD_INDICES_INFO', 'LIKE', 'INDEX_%SCORE', 'NUMERIC', 0.01, 'MEDIUM', 'index score columns'),
  ('MARKETS_WORLD_INDICES_INFO', 'EXACT', 'IF_SUCC_YN', 'FLAG', 0, 'HIGH', 'success flag'),
  ('STOCK_INVEST_INFO', 'LIKE', '%_PRICE', 'NUMERIC', 0.01, 'MEDIUM', 'stock invest price columns'),
  ('STOCK_INVEST_INFO', 'LIKE', '%_RATE%', 'NUMERIC', 0.01, 'MEDIUM', 'stock invest rate columns'),
  ('STOCK_INVEST_INFO', 'LIKE', '%_SCORE', 'NUMERIC', 0.01, 'MEDIUM', 'stock invest score columns'),
  ('STOCK_INVEST_INFO', 'LIKE', '%_DO_YN', 'FLAG', 0, 'HIGH', 'market open/success flags'),
  ('STOCK_INVEST_INFO', 'EXACT', 'IF_SUCC_YN', 'FLAG', 0, 'HIGH', 'final success flag')
ON DUPLICATE KEY UPDATE
  value_type = VALUES(value_type),
  tolerance = VALUES(tolerance),
  default_severity = VALUES(default_severity),
  enabled_yn = 'Y',
  note = VALUES(note),
  updated_at = NOW();
*/

-- ============================================================================
-- FK optional
-- 기본 적용에서는 FK를 사용하지 않는다. 필요 시 신규 검증 테이블끼리만 FK를 추가한다.
-- ============================================================================

/*
ALTER TABLE MARKETS_WORLD_INDICES_INFO_WEEKLY_STAGE
  ADD CONSTRAINT fk_mwii_stage_run
  FOREIGN KEY (run_id) REFERENCES MARKET_WEEKLY_RECHECK_RUN (run_id)
  ON DELETE CASCADE;

ALTER TABLE STOCK_INVEST_INFO_WEEKLY_STAGE
  ADD CONSTRAINT fk_stock_stage_run
  FOREIGN KEY (run_id) REFERENCES MARKET_WEEKLY_RECHECK_RUN (run_id)
  ON DELETE CASCADE;

ALTER TABLE MARKET_WEEKLY_RECHECK_DIFF
  ADD CONSTRAINT fk_market_weekly_diff_run
  FOREIGN KEY (run_id) REFERENCES MARKET_WEEKLY_RECHECK_RUN (run_id)
  ON DELETE CASCADE;

ALTER TABLE MARKET_SITE_ETF_STOCK_INFO_WEEKLY_STAGE
  ADD CONSTRAINT fk_etf_stage_run
  FOREIGN KEY (run_id) REFERENCES MARKET_WEEKLY_RECHECK_RUN (run_id)
  ON DELETE CASCADE;
*/
